<a href="https://colab.research.google.com/github/AbidHeni/Pytorch-tutorial/blob/main/intro_to_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
2+3

5

In [10]:
import torch
import numpy as np


In [33]:
# behy ! nestaamloha kif nhebo n'executiw une commande systeme : !cd ,mkdir ,ls ....
#bch trajaali la liste de toutes les packages l masboubin f python wl version mte7om
!pip list


Package                                  Version
---------------------------------------- --------------------
absl-py                                  1.4.0
absolufy-imports                         0.3.1
accelerate                               1.11.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.2
aiosignal                                1.4.0
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.17.2
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.11.0
anywidget                                0.9.21
argon2-cffi                        

In [34]:
print ("hello")

hello


In [35]:
#lists

mylist =[[1,2,3,4,6],[5,5,6,4,8]]
mylist


[[1, 2, 3, 4, 6], [5, 5, 6, 4, 8]]

In [36]:
#numpy arrays
np1=np.random.rand(2,3)
np1

array([[0.71973488, 0.71807058, 0.13838227],
       [0.12508195, 0.15652919, 0.04566847]])

In [37]:
np1.dtype

dtype('float64')

In [38]:
#tensors multi-dimensional matrix
tensor_2D=torch.randn(3,4) #liste de listes
tensor_2D


tensor([[-0.7826, -0.0507,  0.2134, -1.4618],
        [-0.1872,  0.5524,  1.8216,  0.1594],
        [-1.1783, -1.0927, -0.2196,  0.3393]])

In [39]:
tensor_2D.dtype

torch.float32

In [40]:
tensor_3d=torch.zeros(4,3,2)
tensor_3d


tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [41]:
#create a tensor out of numpy array
tensor1 = torch.tensor(np1)
tensor1

tensor([[0.7197, 0.7181, 0.1384],
        [0.1251, 0.1565, 0.0457]], dtype=torch.float64)

In [42]:
tensor2=torch.arange(10)
tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
#reshape and view
#tensor2=tensor2.reshape(2,6) hethy non valid 5ater 2 ligne andek lezem 6 colonnes f koll lignes w mch bch yzid chy mn ando
tensor2=tensor2.reshape(2,5)
tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [44]:
#autre methode sans connaitre la taille
tensor3=torch.arange(10)
tensor3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
tensor2.reshape(5,-1)#nejem naamel blaaks zeda (-1,5) fixina nbre de colonnes w houa yaatik nbre de ligne mrigl
tensor2
#houni tetbadel tensor2 3ibara 5thet copy

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [46]:
tensor3.view(2,-1)
tensor3
#houni matbadtletch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
#autre remarque
#reshape w view zouz yaamlo update automatique
t1=torch.arange(10)
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
t2=t1.reshape(2,5)
t2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [49]:
t3=t1.view(2,5)
t3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [50]:
# taw bch nbadel f t1
t1[1]=2500
t1

tensor([   0, 2500,    2,    3,    4,    5,    6,    7,    8,    9])

In [51]:
t2

tensor([[   0, 2500,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [52]:
t3

tensor([[   0, 2500,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [54]:
#Slice houma kima f python ki theb te5ou partie ml liste par exemple
t4=torch.arange(20)
t4


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [55]:
t4=t4.reshape(5,4)
t4


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [60]:
#t4[0] 1ere ligne
#t4[1] 2eme ligne
t4[1]

tensor([4, 5, 6, 7])

In [63]:
#3eme ligne 3eme colonne
t4[2][2]

tensor(10)

In [64]:
#3eme ligne 3eme colonne
type(t4[2][2])

torch.Tensor

In [65]:
type(t4)

torch.Tensor

In [69]:
t4 +torch.tensor(1) #equivalent à t4 + 1
#l 1 ya9rah kif tensor w yzid 1 f koll element fel tensor

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

In [74]:
#formule generale pour un tensor de dimension d
#x[start1 : stop1 : step1,    start2 : stop2 : step2   , ...,    startd : stopd : stepd]
#t4 est 2D
t4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [75]:
t4[0:2:1,1:3:1] #equivalent à t4[0:2,1:3]

tensor([[1, 2],
        [5, 6]])

In [76]:
t4[2::2,1:]

tensor([[ 9, 10, 11],
        [17, 18, 19]])

In [77]:
t4[2:,1::2]

tensor([[ 9, 11],
        [13, 15],
        [17, 19]])

In [78]:
t3

tensor([[   0, 2500,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [80]:
t3.shape

torch.Size([2, 5])

In [82]:
torch.tensor(5).shape

torch.Size([])

In [84]:
t4[0][0]

tensor(0)

In [86]:
torch.tensor([5]).shape

torch.Size([1])

In [87]:
torch.tensor([[5]]).shape

torch.Size([1, 1])

In [88]:
t4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [90]:
math_tensor=torch.arange(2,22).reshape(5,4)
math_tensor

tensor([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])

In [91]:
#addition
math_tensor+t4

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24],
        [26, 28, 30, 32],
        [34, 36, 38, 40]])

In [92]:
math_tensor.add(t4)

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24],
        [26, 28, 30, 32],
        [34, 36, 38, 40]])

In [93]:
torch.add(math_tensor,t4)

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24],
        [26, 28, 30, 32],
        [34, 36, 38, 40]])

In [94]:
#soustraction
torch.sub(math_tensor,t4)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

In [95]:
t4 - math_tensor

tensor([[-2, -2, -2, -2],
        [-2, -2, -2, -2],
        [-2, -2, -2, -2],
        [-2, -2, -2, -2],
        [-2, -2, -2, -2]])

In [96]:
math_tensor.sub(t4)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

In [97]:
#multiplication
t4*math_tensor

tensor([[  0,   3,   8,  15],
        [ 24,  35,  48,  63],
        [ 80,  99, 120, 143],
        [168, 195, 224, 255],
        [288, 323, 360, 399]])

In [98]:
t4.mul(math_tensor)

tensor([[  0,   3,   8,  15],
        [ 24,  35,  48,  63],
        [ 80,  99, 120, 143],
        [168, 195, 224, 255],
        [288, 323, 360, 399]])

In [99]:
torch.mul(t4,math_tensor)

tensor([[  0,   3,   8,  15],
        [ 24,  35,  48,  63],
        [ 80,  99, 120, 143],
        [168, 195, 224, 255],
        [288, 323, 360, 399]])

In [100]:
#division
#3/0 tji infinity
math_tensor/t4

tensor([[   inf, 3.0000, 2.0000, 1.6667],
        [1.5000, 1.4000, 1.3333, 1.2857],
        [1.2500, 1.2222, 1.2000, 1.1818],
        [1.1667, 1.1538, 1.1429, 1.1333],
        [1.1250, 1.1176, 1.1111, 1.1053]])

In [101]:
math_tensor.div(t4)

tensor([[   inf, 3.0000, 2.0000, 1.6667],
        [1.5000, 1.4000, 1.3333, 1.2857],
        [1.2500, 1.2222, 1.2000, 1.1818],
        [1.1667, 1.1538, 1.1429, 1.1333],
        [1.1250, 1.1176, 1.1111, 1.1053]])

In [102]:
#de mem donc puiss .pow yaamel l'element puissance l'element li m9ablo fel tensor le5er
